sudo: required
language: cpp
compiler:
  - g++
  - clang
services: docker
before_install:
  - docker pull hbrinj/littlebbuild
script:
  - docker run -e CC=$CC -e CXX=$CXX -v $(pwd)/.:/littleb hbrinj/littlebbuild 
